apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rh5g9bw2l-java-quarkus
  janus-idp.io/tekton: rh5g9bw2l-java-quarkus
  backstage.io/kubernetes-id: rh5g9bw2l-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rh5g9bw2l-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
